[tool.unasyncd.files]
"src/rabbitmq_management/http_clients/async_client.py" = "src/rabbitmq_management/http_clients/client.py"
"src/rabbitmq_management/management_api/_async/" = "src/rabbitmq_management/management_api/_sync/"
"tests/unit/http_clients/test_async_client.py" = "tests/unit/http_clients/test_client.py"
"tests/unit/management_api/test_async_management_api.py" = "tests/unit/management_api/test_management_api.py"
"tests/unit/management_api/test_async_channels_api.py" = "tests/unit/management_api/test_channels_api.py"
"tests/unit/management_api/test_async_consumers_api.py" = "tests/unit/management_api/test_consumers_api.py"
"tests/unit/management_api/test_async_auth_api.py" = "tests/unit/management_api/test_auth_api.py"
"tests/unit/management_api/test_async_bindings_api.py" = "tests/unit/management_api/test_bindings_api.py"
"tests/unit/management_api/test_async_connections_api.py" = "tests/unit/management_api/test_connections_api.py"
"tests/unit/management_api/test_async_definitions_api.py" = "tests/unit/management_api/test_definitions_api.py"
"tests/unit/management_api/test_async_exchanges_api.py" = "tests/unit/management_api/test_exchanges_api.py"
"tests/unit/management_api/test_async_health_api.py" = "tests/unit/management_api/test_health_api.py"
"tests/unit/management_api/test_async_nodes_api.py" = "tests/unit/management_api/test_nodes_api.py"
"tests/unit/management_api/test_async_parameters_api.py" = "tests/unit/management_api/test_parameters_api.py"
"tests/unit/management_api/test_async_permissions_api.py" = "tests/unit/management_api/test_permissions_api.py"
"tests/unit/management_api/test_async_policies_api.py" = "tests/unit/management_api/test_policies_api.py"
"tests/unit/management_api/test_async_queues_api.py" = "tests/unit/management_api/test_queues_api.py"
"tests/unit/management_api/test_async_users_api.py" = "tests/unit/management_api/test_users_api.py"
"tests/unit/management_api/test_async_vhosts_api.py" = "tests/unit/management_api/test_vhosts_api.py"

[tool.unasyncd.add_replacements]
"AsyncClient" = "Client"
"AsyncHTTPClient" = "HTTPClient"
"AsyncRMQManagementAPI" = "RMQManagementAPI"
"AsyncAuthAPI" = "AuthAPI"
"AsyncBindingsAPI" = "BindingsAPI"
"AsyncChannelsAPI" = "ChannelsAPI"
"AsyncConnectionsAPI" = "ConnectionsAPI"
"AsyncConsumersAPI" = "ConsumersAPI"
"AsyncDefinitionsAPI" = "DefinitionsAPI"
"AsyncExchangesAPI" = "ExchangesAPI"
"AsyncHealthAPi" = "HealthAPI"
"AsyncNodesAPI" = "NodesAPI"
"AsyncParametersAPI" = "ParametersAPI"
"AsyncPesmissionsAPI" = "PermissionsAPI"
"AsyncTopicPermissionsAPI" = "TopicPermissionsAPI"
"AsyncOperatorPoliciesAPI" = "OperatorPoliciesAPI"
"AsyncPoliciesAPI" = "PoliciesAPI"
"AsyncQueuesAPI" = "QueuesAPI"
"AsyncUsersAPI" = "UsersAPI"
"AsyncVHostsAPI" = "VHostsAPI"
"aclose" = "close"
"async_http_client" = "http_client"
"async_management_api" = "management_api"
